#!/bin/bash

#----------------------- gst
date -R > $GITOUT
for git in $(find -type d -name .git | xargs dirname) ; do 
    pushd $git > /dev/null
    printf "_______________ In repo: %-40s  _____________________\n" "$(pwd | sed 's/^\/cygdrive//')" | tee -a $GITOUT
    echo -n "INITIAL: " | tee -a $GITOUT
    for BR in $(git branch -avv | grep -v HEAD | sed 's/^\*/ /;s/  */ /g' | cut -d' ' -f 3 | sort | uniq) ; do
        echo -e "$(git rev-list --max-parents=0 $BR)" ; 
    done | sort | uniq | tr '\n' ' ' 2>&1 | tee -a $GITOUT                                                                                      
    echo | tee -a $GITOUT                                                                                      
    git remote -v 2>&1 | tee -a $GITOUT                                                                                      
    echo "---end---" | tee -a $GITOUT                                                                                      
    popd > /dev/null
done
echo "===END===" | tee -a $GITOUT                                                                                      

# export GITLESSOPT='-p clean'
#less -N -S $GITLESSOPT $GITOUT
less -N -S $GITOUT
