#!/bin/bash

#----------------------- gst
date -R > $GITOUT
for git in $(find -type d -name .git | xargs dirname) ; do 
    pushd $git
    echo "Visiting $(pwd)"
    printf "_______________ In repo: %-40s  _____________________\n" "$(pwd | sed 's/^\/cygdrive//')" | tee -a $GITOUT
    git $* 2>&1 | tee -a $GITOUT                                                                                      
    popd
done

# export GITLESSOPT='-p clean'
#less -N -S $GITLESSOPT $GITOUT
less -N -S $GITOUT
