#!/bin/bash

#----------------------- gst
date -R > $GITOUT
for git in $(find -type d -name .git | xargs dirname) ; do 
    pushd $git
    echo "Visiting $(pwd)"
    printf "%-15s%s\n" "$(pwd | sed 's/^.*\///')" "$(git status | grep -E -v '[()]|^ *$' | grep -v 'Your branch is ' | sed 's/ directory / tree /')" >> $GITOUT
    echo '________________________________=====' >> $GITOUT
    popd
done

# export GITLESSOPT='-p clean'
less -N -S $GITLESSOPT $GITOUT
